version: '3'

services:
 init_postgres:
  image: postgres:latest
  ports:
   - "5433:5432"
  networks:
   - elt_network
  environment:
   POSTGRES_DB: source_db
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: secret
  volumes:
   - ./init_db_data/init.sql:/docker-entrypoint-initdb.d/init.sql

 elt_script:
  build:
   context: ./script
   dockerfile: Dockerfile
  command: ["python", "elt.py"]
  networks:
   - elt_network
  depends_on:
    - init_postgres
    - last_postgres

 last_postgres:
  image: postgres:latest
  ports:
   - "5434:5432"
  networks:
   - elt_network
  environment:
   POSTGRES_DB: dest_db
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: secret


networks:
 elt_network:
  driver: bridge